Pin elasticsearch version
Yelp/elastalert pull request #2206
Opened 2019-04-14 20:26 UTC by caleb15

see #2203 and #2204 

Alternatively if #2194 is merged in soon this PR can be ignored, as I presume #2194 would fix it.

2021-01-16 11:58 UTC, nsano-rururu commented
Can you resolve conflicts please :)

2022-01-22 17:34 UTC, nsano-rururu approved these changes

2022-01-22 17:36 UTC, nsano-rururu requested changes
elasticsearch<7.0.0
   ↓
elasticsearch==7.0.0

2022-01-24 19:20 UTC, caleb15 commented
Actually I think this was fixed already by https://github.com/Yelp/elastalert/pull/2194

2022-01-24 19:20 UTC, closed without merging